language: python
python:
- "2.7"
- "3.5"
- "3.6"
- pypy
install:
- pip install -r requirements.txt -r test-requirements.txt
script:
- nosetests
deploy:
  provider: pypi
  user: daveshawley
  password:
    secure: mro/z81aQGRtN7PiHl1JK962OLOVeoFf3ZTIW/eqo3RBlgbO6IhZtG1tsdIw56QcfpoJ1Vxy0mo1y8Cwh1fNjVHf1nB808GeRfw7oGuhRaj2tJxVylfVnR/kV+m0NXHpo7+Zib6/sA4VmWwx33HKu20UdBtnx75r0vlnx6lpyPqSOald0hA8TqrV7MfRjCD56HH2dkpNHgFBvIwRV50XBUINdQdDEsoiMRMZTiUmAuwyX8gUkQAcVweCBhO28jf0k7vjDbqb4AejslVTuw862nYAv6aeqKOwY0FfP/kv2jABMdW7PvXZGohNmNEGfi7cwamHgM6/kZfrDZ0Rzf7C00UIHED3B8p2slv94SjMUehuVuP+iD/ueT9ZCP7ycGzn5yszRyMMtV6fBv3NhcLs0WaT2TB3GhbPca9Ub2RfTcMLbBZVxig+gsNyVAYzMCuoiW6JKZSRkEE2KCJkHrESoDD8ZySSmBcb8lDye7aL6lRURaaWdL9uYBfJzMBGdMWrERiYqGtjOtboOYL0ROOJMxWY+RLro/JKgKzVcuNDNCbYE/fV3QF1UZUJMcGmBzgoyY5Cp2ccVChBdV7EKSGIBXHtOMlVHv86J0nHHbL7BcaEZnZoraD4FSFFrmxTRKOO5k4IxlnpT9mMS8bqVbCfTAeC6gXcGD9l8zQnxUIrn9Y=
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: dave-shawley/glinda
    all_branches: true
    python: 3.6
